name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Backend Tests
        run: ./gradlew test

      - - name: Upload Test Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: test-results
            path: src/test/java/service/FrageServiceTest.java


      - name: Upgrade Gradle Wrapper
        run: ./gradlew wrapper --gradle-version=8.3
